### PR TITLE
Dependency logic

### PR DESCRIPTION
**Pull request by benjamink**
Fixes issues with installing via Git (packages don't work on Ubuntu 14.04) where the 'icingaweb2' package could not be found as a dependency.

Fixes deprecation warnings thrown by recent versions of PHP (5.5+) with how the comments are prefixed in the various INI templates.

### CODE REVIEW

**Comment by Civil** [comment]
Please merge that PR, otherwise Icingaweb2 really doesn't install in some cases (and also will complain about deprecated comments).

**Comment by arioch** [comment]
Merged: https://github.com/Icinga/puppet-icingaweb2/commit/8b14edcf9191a8615ffba12294c36abf4d18efc2

Thanks!

**Comment by arioch** [comment]
@lazyfrosch could you close this ticket and/or give me permission to do it myself.

**Comment by dnsmichi** [comment]
Added missing collaborators, try again @arioch please

**Comment by arioch** [comment]
Looking good @dnsmichi!

**Pull request closed without merging**
