### PR TITLE
update dependencies and add missing ones

### PR DESCRIPTION
**Pull request by SimonHoenscheid**

### CODE REVIEW

**Comment by martialblog** [comment]
Did you also notice this due to the Jessie Backports?

**Comment by SimonHoenscheid** [comment]
@martialblog I noticed the module has unfulfilled dependencies, if the dependent modules are up to date

**Comment by lbetz** [comment]
The both package management modules aren't included because they are optional. They have to be used if you set parameter 'manage_repo' to true.

**Comment by lbetz** [comment]
But we discussed that today and we will use it as described in this PR.

**Comment by lazyfrosch** [comment]
@lbetz Status? Keep apt and zypprepo? Or remove them here?

**Comment by lazyfrosch** [comment]
Closing in favor of #226

**Pull request closed without merging**
