### PR TITLE
Add compatibility with Debian Stretch

### PR DESCRIPTION
**Pull request by intrigeri**

### CODE REVIEW

**Comment by intrigeri** [comment]
Not sure how to fix the Travis tests, that fail due to `operatingsystemmajrelease` not being set :/

**Comment by hboetes** [comment]
The same package versions also go for ubuntu xenial, which would not be matched by this patch. Isn't is smarter to check for the generic package names? Would `php-foo` instead of `php5-foo` also work on older releases?

```
os => {
  architecture => "amd64",
  distro => {
    codename => "xenial",
    description => "Ubuntu 16.04.2 LTS",
    id => "Ubuntu",
    release => {
      full => "16.04",
      major => "16.04"
    }
  },
  family => "Debian",
  hardware => "x86_64",
  name => "Ubuntu",
  release => {
    full => "16.04",
    major => "16.04"
  },
  selinux => {
    enabled => false
  }
}
```

**Comment by intrigeri** [comment]
Hi!

Thanks for taking a look :)

Han Boetes:
> The same package versions also go for ubuntu xenial, which would not be matched by this patch.

Sorry, I don't use Ubuntu to I'd rather keep this PR focused on Debian. I expect my PR will pave the way for users of recent Ubuntu to add support for their favorite distro though.

> Isn't is smarter to check for the generic package names? Would `php-foo` instead of `php5-foo` also work on older releases?

This would be nice, but sadly it won't work: e.g. Debian 8 (Jessie) has no `php-gd` package. Thankfully, as you can see in my PR, this changed with Debian 9 (Stretch) and generic, version-less package names are now used, so once we stop supporting Debian 8 or older the code can be simplified :)

**Comment by bobapple** [comment]
This seems not relevant with the current development. Like with our [icinga2](https://github.com/Icinga/puppet-icinga2) module, our approach is to support LTS versions only.

**Comment by intrigeri** [comment]
> our approach is to support LTS versions only.

FYI Debian releases have been LTS (5 years, just like Ubuntu) for a while: see the "Long-term support" column on https://en.wikipedia.org/wiki/Debian_version_history#Release_table for the details.

Is that sufficient to qualify as LTS in the context of this project and reopen this conversation?

**Pull request closed without merging**
