### PR TITLE
option to install modules as package

### PR DESCRIPTION
**Pull request by pulecp**
We run Icinga Web 2 in an environment without access to github.com so we have to package the `generictts` and `graphite` plugins ourselves (or find another way how to get there).

### CODE REVIEW

**Comment by joernott** [comment]
It would be cool to enable this also for the other supported modules to allow all the dfferent methods of installing a resource as offered by the underlying icingaweb2::module

**Comment by pulecp** [comment]
@joernott indeed, I added the same options to the rest of modules and force-pushed my changes.

**Comment by joernott** [comment]
cool, thanks

**Comment by lbetz** [comment]
Will be merged/reworked when the Icinga team serves packages.

**Comment by lbetz** [comment]
Ok, the Icinga team takes too long.

**Comment by zilchms** [comment]
Is there a reason to the additional dots in the cube.pp and director.pp am not aware off? Seems to me this is causing some failed checks in the Travic CI.
And the merge pushed that failing state to the master (and consecutively to all following commits).
Seems like a bad starting point for working on a milestone feature, when the master branch is failing checks on its own.

**Comment by lbetz** [comment]
Sorry, I don't understand which dots?

**Comment by zilchms** [comment]
In the cube.pp at line 31: String**.** =>
And in the director.pp at line 82: String**.** =>

These dots seem to make the CI fail. Is it on purpose as a sort of reminder? Since above a problem with the icinga packages was described.

**Comment by lbetz** [comment]
Now I see, shit.

**Comment by zilchms** [comment]
Lastest commit seems to have fixed the Static checks. No there are problems in the dynamic Checks. Although I am not sure which of the 2 pull requests is responsible.
Maybe a revert of the master to bevore the merge of the 2 Pull requests and a reapplication of both requests (without the typo) would be a clean way to fix that and lets the corresponding people know if their code is the one with errors?
(Not sure, have never worked on a big gitproject outside of my workplace)

**Pull request merged**
