### PR TITLE
Fix authentication configuration

### PR DESCRIPTION
**Pull request by lazyfrosch**
auth_method => external
  Was not handled at all, but provided as defined type.

admin_users => [ list ]
  Was written into the wrong ini value

I'll add a few lint fixes soon.

### CODE REVIEW

**Comment by arioch** [comment]
These are easy to fix...

```
$ bundle exec rake spec
*snip*
Failures:

  1) icingaweb2 with parameter: admin_users should contain Icingaweb2::Config::Roles[Admins] with role_name =~ /_admin_users_/
     Failure/Error: should contain_icingaweb2__config__roles('Admins').with(
       expected that the catalogue would contain Icingaweb2::Config::Roles[Admins] with role_name set to /_admin_users_/ but it is set to "Admins"
     # ./spec/classes/icingaweb2_spec.rb:58:in `block (3 levels) in <top (required)>'

  2) icingaweb2 with parameter: auth_resource should contain Icingaweb2::Config::Authentication_database[Local Database Authentication] with auth_resource =~ /_auth_resource_/
     Failure/Error: should contain_icingaweb2__config__authentication_database('Local Database Authentication').with(
       expected that the catalogue would contain Icingaweb2::Config::Authentication_database[Local Database Authentication]
     # ./spec/classes/icingaweb2_spec.rb:76:in `block (3 levels) in <top (required)>'

Finished in 8.35 seconds (files took 0.51501 seconds to load)
76 examples, 2 failures, 10 pending
```

Will you fix those or would you like a pull request?

**Comment by lazyfrosch** [comment]
Yep, working on it.

BTW, I've enabled the Travis builds for that repo...

**Comment by arioch** [comment]
:+1:

**Comment by lazyfrosch** [comment]
@arioch would it be okay for you to change the fixtures to HTTPs links?

**Comment by arioch** [comment]
That would save me the trouble of doing so. :+1:

**Comment by lazyfrosch** [comment]
Should be ready for merge :)

**Comment by arioch** [comment]
Merged upstream!

**Pull request merged**
