### PR TITLE
WIP: Module management

### PR DESCRIPTION
**Pull request by lazyfrosch**
I implemented basic module management.

Could you please review? Not yet finished...

### CODE REVIEW

**Comment by arioch** [comment]
Looking good so far. :+1: 

Did you plan to add rspec coverage too?
If not I'll look into it.

**Comment by lazyfrosch** [comment]
Yes sure.

Are you okay with the parameter naming? I though about including managed, but that would be very long...

**Comment by arioch** [comment]
I'm ok with the parameter naming. 
It's short and it's predictable as to what it performs.

Something I was thinking about while driving home: how about we make a $modules parameter?

F.i. as an array:
```
class { 'icingaweb2':
   modules => [ 'monitoring', 'pnp4nagios' ],
}
```

or even as a hash allowing us to configure the modules as well:

```
class { 'icingaweb2':
  modules => { 
    monitoring =>  {
      enable => true,
      key    => 'value',
    },
    pnp4nagios =>  {
      enable => true,
      key    => 'value',
    },
  },
}
```

**Comment by lazyfrosch** [comment]
I like the hash idea, but it will require us to make every module a class :)

**Comment by arioch** [comment]
That's right. Makes easier to maintain too. :)

**Comment by ckaenzig** [comment]
This code seems to work well as it is, except that I use `install_method => package` and the module package is missing. On Debian, it should install `icingaweb2-module-monitoring`.

**Comment by dnsmichi** [comment]
You'll probably need a way to define whether a module is builtin, or not. 'monitoring' as such is, while 'pnp4nagios' must be installed seperately. Enabling and configuring the module is independent from that.

**Comment by bodsch** [comment]
I like this.
I've the same idea :)

**Comment by Ziaunys** [comment]
Is there any chance that this will get merged soon? I'm really looking forward to using these improvements. I have a fork where I've added a few things, but there are far more improvements in this PR. One thing that I added in my fork is a 'authentication_ldap' define type which basically references the 'resource_ldap' define type. It's simple enough that you could add it here, I could make a PR against this branch, or I can just open a ticket to add it.

**Comment by bodsch** [comment]
How can i merge this PR with my Repository to test an help for development?

**Comment by arioch** [comment]
@bodsch this should get you going:

```
git checkout -b module-management
git remote add lazyfrosch https://github.com/lazyfrosch/puppet-icingaweb2.git
git pull --rebase lazyfrosch module-management
```

**Comment by lazyfrosch** [comment]
This is fairly outdated, so closing it

**Pull request closed without merging**
