### PR TITLE
Loosen concat version restrictions

### PR DESCRIPTION
**Pull request by quixoten**

### CODE REVIEW

**Comment by bobapple** [comment]
The tests for Pupppet 3 are failing, it doesn't look like Puppet 3 is working with concat v4.0.1

**Comment by dgoetz** [comment]
@bobapple: Puppetlabs dropped Puppet 3 support for concat with 3.0.0.

**Comment by quixoten** [comment]
Reverted to concat 2.2.1 for testing.

**Comment by bobapple** [comment]
@dgoetz Puppet 3 itself is EOL, but we're keeping the module compatible

**Comment by quixoten** [comment]
I think this should be okay to merge now.

**Pull request merged**
