### PR TITLE
Properly absent empty values for config::roles

### PR DESCRIPTION
**Pull request by lazyfrosch**
Also added validation and spec

resolves #14

### CODE REVIEW

**Comment by lazyfrosch** [comment]
Still thanks to @timogoebel :)

**Comment by arioch** [comment]
Looking good guys. :+1:

**Comment by lazyfrosch** [comment]
I'm still wondering why Travis fails, the spec runs on my system without a problem...

**Comment by arioch** [comment]
Weird. Travis mentions ```126 examples, 1 failure, 16 pending```.
When I run the specs on feature-delete-undef-settings it says ```112 examples, 0 failures, 13 pending```.

**Comment by lazyfrosch** [comment]
Maybe a temporary error: https://travis-ci.org/lazyfrosch/puppet-icingaweb2/builds/66175271

**Comment by lazyfrosch** [comment]
Something is wrong with this PR:
```
git clone https://github.com/Icinga/puppet-icingaweb2
cd puppet-icingaweb2/
git fetch refs/pull/15/merge   # used by Travis
git show FETCH_HEAD
```

Will contact GitHub about it...

**Comment by lazyfrosch** [comment]
Hah, GIT merge weirdness....

Since @arioch  commited 5aa065c9996a7c9a17e1ea814409602d12e9a995 and @timogoebel 's commit was based on an earlier commit, the merge to master did some weird changes.

Rebased, amended and pushed.

Btw. @arioch Travis tests the merged version of a PR, never the branch to merge, kinda smart :)

**Comment by arioch** [comment]
I've merged to ```develop``` branch.
Thanks @lazyfrosch and @timogoebel!

**Pull request closed without merging**
