### PR TITLE
Add vpsheredb module

### PR DESCRIPTION
**Pull request by JonasVerhofste**
This adds puppet code to manage the vspheredb-module, like other modules (monitoring, director, etc) are managed (which this code is heavily based on).

### CODE REVIEW

**Comment by lbetz** [comment]
Thx a lot, looks pretty nice.

**Comment by JonasVerhofste** [comment]
@lbetz Apparently I wrote some of it not entirely awake, should all be fixed now!

**Comment by lbetz** [comment]
Looks now equal to the director classes and very important, the management of an mysql::db is gone. Thx.

**Comment by JonasVerhofste** [comment]
Yes, was a bit overzealous in copying from our internal code :p

**Pull request merged**
