### PR TITLE
Add possibility to set auth_backend to ldap

### PR DESCRIPTION
**Pull request by n00by**
next to the already existing possibilities db and external. If auth_backend is set
to ldap an ldap ressource and an ldap authentication configuration is generated.

Also support for ldap encryption is added.

### CODE REVIEW

**Comment by lbischof** [comment]
Whats preventing this from being merged? We need this functionality.

**Comment by n00by** [comment]
@arioch please bump

**Comment by phihos** [comment]
+1 for merge

**Comment by arioch** [comment]
Excellent stuff, thank you. 👍 
Merged upstream.

**Pull request closed without merging**
