### PR TITLE
Feature/attempting to add freebsd support

### PR DESCRIPTION
**Pull request by rick-pri**
I've not done anything with regards to testing with Ruby, so there're no alterations to the tests in this PR.  But I wanted to get the ball rolling to get this eventually accepted back into the project as otherwise it'll just sit in my account.

I'm going to need direction for what I'm going to need to change and where.  I don't mind learning but I have no idea where I need to start given that I can only hack Ruby code.

### CODE REVIEW

**Comment by lazyfrosch** [comment]
Any news here? @rick-pri

**Comment by rick-pri** [comment]
> Any news here? @rick-pri

We seem to have been using this forked version for about 2 years.  I would still need mentoring though adding tests (I still am no better at Ruby and Puppet stuff now than I was two years ago.)

**Comment by lbetz** [comment]
thx

**Comment by rick-pri** [comment]
> thx

Don't thank me just yet I'm just testing this out :)  However,, I'm having to do this because recent package update changes have broken our monitoring servers so I should have this done in fairly short order.

P.S. The change to use data has made this far simpler to implement.

**Comment by rick-pri** [comment]
Okay, @lbetz I ran through an update of the server and then deploying this PR and I now have a working icingaweb2 frontend.

**Comment by rick-pri** [comment]
> Why the management of group $conf_group is required?

Hi @lbetz I don't remember is the honest answer but I think that the group was being used and causing an issue when it was wheel or whatever the default was; maybe `www`?  I think that this will be something to do with the FreeBSD package which I've had to work around here.

**Comment by lbetz** [comment]
I'd like to have a look to the group before releasing it.

**Pull request merged**
