### PR TITLE
Postgresql initialize

### PR DESCRIPTION
**Pull request by vrf888**
Added intitialization for PostgreSQL DB.

### CODE REVIEW

**Comment by arioch** [comment]
Finally got around to checking your patches but your postgresql_initialize branch is no longer available.
Could you push it again?

**Comment by Karen09** [comment]
+1

**Comment by havauxm** [comment]
Hi, is there any progress about this pull request? Thanks

**Comment by kalinux** [comment]
Btw . I have tested it im my setup . and its working very well . so `

**Comment by bobapple** [comment]
Thank you @vrf888 
This feature has been added in a29902d45e0e2453ae6e3831cc7e72337aa412ad

**Pull request closed without merging**
