### PR TITLE
make icingacli package configurable per os family

### PR DESCRIPTION
**Pull request by XnS**

### CODE REVIEW

**Comment by bobapple** [comment]
@XnS which repository are you using? We're not providing a package called `icingaweb2-icingacli` on packages.icinga.com.

**Comment by XnS** [comment]
@bobapple official SLES repository - obs://build.opensuse.org/server:monitoring (SLES 12 SP3 Monitoring (x86_64))

**Comment by bobapple** [comment]
@XnS as far as I can see that's an opensuse repository. You should use the official repository on packages.icinga.com for SLES

**Comment by XnS** [comment]
@bobapple Im now trying to use the official packages/repos by setting
```
    manage_repo    => true,
    manage_package => true,
```
Unfortunately the packages are still not used, because the added repository has the same prio as others:
```
Refreshing service 'spacewalk'.
#  | Alias                                               | Name                                                   | Enabled | GPG Check | Refresh | Priority
---+-----------------------------------------------------+--------------------------------------------------------+---------+-----------+---------+---------
 1 | icinga-stable-release                               | icinga-stable-release                                  | Yes     | (r ) Yes  | No      |   99    
 2 | spacewalk:sles-12-sp3-adv_systems_management-x86_64 | SLES 12 SP3 Advanced System Management Module (x86_64) | Yes     | (  ) No   | Yes     |   99    
[...]
 6 | spacewalk:sles-12-sp3-monitoring-x86_64             | SLES 12 SP3 Monitoring (x86_64)                        | Yes     | (  ) No   | Yes     |   99    
```

Is it possible to set the prio to 98 in zypprepo?

**Comment by bobapple** [comment]
@XnS that makes sense, can you open a separate PR?

**Pull request closed without merging**
