### PR TITLE
fix travis-ci failures

### LINKED ISSUE #269: travis-ci `check:git_ignore` check is failing on master
```
bundle exec rake $CHECK
rake aborted!
File specified in .gitignore has been committed
```

### LINKED ISSUE #271: travis-ci rubocop check is failing on master
```
25 files inspected, 1013 offenses detected
RuboCop failed!
```

### PR DESCRIPTION
**Pull request by jhoblitt**
Resolves #269 
Resolves #271

### CODE REVIEW

**Comment by jhoblitt** [comment]
It seems that puppet-lint was failing too...

**Comment by jhoblitt** [comment]
Ping?

**Comment by lbetz** [comment]
Sorry, I was on vacation and my work on puppet-icinga2 is pending.

**Comment by lbetz** [comment]
thx for your work.

**Pull request merged**
