### PR TITLE
Add Grafana module

### PR DESCRIPTION
**Pull request by neubi4**
Added class and tests for installing the module icingaweb2-module-grafana https://github.com/Mikesch-mp/icingaweb2-module-grafana.

Sample in README.md

### CODE REVIEW

**Comment by bobapple** [comment]
Thank you for the effort @neubi4 
Our current approach is to install modules developed by the community through the `icingaweb2::module` defined type and to include official modules directly into this Puppet module as classes.

**Comment by baurmatt** [comment]
>Our current approach is to install modules developed by the community through the `icingaweb2::module` defined type

Meaning everyone has to implement the module by themself?

**Comment by dnsmichi** [comment]
I've found this example very convenient.

https://github.com/Icinga/puppet-icingaweb2/blob/master/examples/module_map.pp

**Comment by bobapple** [comment]
I'm currently accepting only Icinga Web 2 modules from the Icinga repositories, referring to them as "official" modules. All other modules (community modules) have to use the `icingaweb2::module` type. 

It's not a technical decision, rather an organizational. Technically it's possible to add all modules, but we can never be sure how long modules from the community are maintained. Removing Icinga Web 2 modules from this Puppet Module is much harder then adding them, from the "decision making" point of view.

Hope this makes sense to you.

**Comment by baurmatt** [comment]
I can understand the reason for this decision even thought i dislike the idea of everyone hacking there own solution for the installation/configuration of a 3rd party module.

**Comment by noqqe** [comment]
Strong ACK @baurmatt 

Its not that we wanna have you deliver 3rd party modules in the default installation of icingaweb2. Its just the community puppet module.

Someone (@neubi4) made the effort and implemented the module. So give the users of your software the choice benefit from that work. Rejecting working functionality for "political reasons" is very sad.

**Comment by dnsmichi** [comment]
I don't really understand the stress in here.

https://github.com/Icinga/puppet-icingaweb2#defined-type-icingaweb2module

offers anything you need to install, download and configure Icinga Web 2 modules. Is there anything missing by using this defined type?

**Comment by baurmatt** [comment]
No, there isn't anything missing as far as i'm aware of. It's just feels like a bad idea that everyone creates their own wrapper around `icingaweb2::module` for commonly used community modules.

**Comment by neubi4** [comment]
At least it would be nice to have an parameter in the `icingaweb2` class which i could give a hash and it would use puppets `create_ressources()` function with the `icingaweb2::module` define, so you could simply configure this via hiera only.

Since we are not using puppet anymore to configure icinga2 at the T-Systems MMS (we switched to docker, we have a talk about this tomorrow at the OSMC) i currently do not have time to create a PR for this.

**Pull request closed without merging**
