### PR TITLE
Fixed dependency errors on mod deployments

### PR DESCRIPTION
**Pull request by jkroepke**

### CODE REVIEW

**Comment by lazyfrosch** [comment]
Catching up with issues, web_root is not the correct path, config_dir should be correct.

How had you had problems with it?

**Comment by jkroepke** [comment]
@lazyfrosch 

Without this PR, I got this error:

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Invalid relationship: Ini_setting[deployment auth token] { require => File[/etc/icingaweb2/modules/deployment] }, because File[/etc/icingaweb2/modules/deployment] doesn't seem to be in the catalog
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

Because the file resource contains the web_root dir.

https://github.com/Icinga/puppet-icingaweb2/blob/master/manifests/mod/deployment.pp#L29

Using RHEL7.2

**Comment by druchoo** [comment]
I get same error. Also on EL 7.2 w/ Puppet 4.8.1

**Comment by lazyfrosch** [comment]
Getting your problem, but the real issue is that the class creates the module directory, but not the config directory.

I guess `ini_setting` will create the path when it's missing. See #76 for a fix.

**Pull request closed without merging**
