### PR TITLE
Manage logging directory and file

### LINKED ISSUE #172: Logging directory is not created by module
## Expected Behavior
Installing the module should create the logfile directory (`/var/log/icingaweb2` by default)
## Current Behavior
When using the module, the logging directory is not created, and therefore logs are not being written anywhere
## Possible Solution
Create the directory before setting the logging path
## Steps to Reproduce (for bugs)
1. Use the module to install icingaweb2 
2. Access the Configuration -> Application in the icingaweb2 UI
3. Try to save the current configuration
4. An error message saying `File path is not writable` will appear beneath the logging configuration, due to the absence of the logging dir.

## Context
As a workaround, I am creating the folder manually before running the module, but this seems like something the module can handle.
## Your Environment

* Module version (`puppet module list`): 1.0.6
* Puppet version (`puppet -V`): 4.7.0
* Operating System and version: 16.04.2 LTS

### PR DESCRIPTION
**Pull request by baurmatt**
Fixes #172

### CODE REVIEW

**Comment by bobapple** [comment]
I would prefer to create the directory and file without setting the group to `adm`

**Comment by baurmatt** [comment]
Which group would you prefer? From my understanding `adm` is the default group for log files. You can add user to this group which should have only read access.

**Comment by bobapple** [comment]
I'm not sure if all distributions and syslog daemons actually use the `adm` group. I've seen it on Debian and Ubuntu, but not on RHEL or SLES. Therefore I thought it would be better to not set the group at all.

**Comment by baurmatt** [comment]
Seems like the group exists on RHEL/SLES but isn't used. I therefor removed the owner and group settings. The defaults from:

```puppet
  File {
    mode  => '0660',
    owner => $conf_user,
    group => $conf_group
  }
```
are now getting used.

**Pull request merged**
