### PR TITLE
enable LDAP Auth

### PR DESCRIPTION
**Pull request by bodsch**
Hi!

Here are my changes for LDAP-Auth. Its tested with CentOS 6.6.
Its works again our Customer Directoryservice.
Sorry, i remove the used ini_settings() again templates and concat(). Thats lock smarter for me an reduce the Code significant.

Greetings from Hamburg,
 Bodo

### CODE REVIEW

**Comment by arioch** [comment]
Hi @bodsch,

Thanks for your contribution!

Could you split the functionality to feature branches and send separate pull requests instead? 
One containing LDAP support and another for Livestatus. Preferably rebase to one or two commits each. That way it's a lot more clear to sort out later on what's changed and which functionality has been added.
Also adding spec tests for any new functionality is required.

I've seen a bunch of unnecessary style changes. Please keep the Puppetlabs styleguide in mind and use puppet-lint when not sure. We'd like to keep the code as clean as possible.

F.i.:
stylechanges

And lastly I can't accept any patches reverting ini_settings().
Concat simply isn't suitable for ini files in the long run.

**Comment by bodsch** [comment]
Am Mittwoch, 15. April 2015, 03:06:08 schrieb Tom De Vylder:

Hi Tom!

> Could you split the functionality to feature branches and send separate pull
> requests instead? One containing LDAP support and another for Livestatus.
> Preferably rebase to one or two commits each. That way it's a lot more
> clear to sort out later on what's changed and which functionality has been
> added. Also adding spec tests for any new functionality is required.

I do my best.
But, i think i need help by the splitting. My git knowhow are rudimentary ...

> I've seen a bunch of unnecessary style changes. Please keep the Puppetlabs
> styleguide in mind and use puppet-lint when not sure. We'd like to keep the
> code as clean as possible.

Okay.
I change my own styleguide.

> And lastly I can't accept any patches reverting ini_settings().
> Concat simply isn't suitable for ini files in the long run.

:(
Okay, i change it back to ini_settings().


I need more time (and coffe) .. :)

Greetings,
 Bodo

**Comment by arioch** [comment]
I'll close this PR for now but send in some feature patches instead. :)

**Comment by bodsch** [comment]
Am Mittwoch, 15. April 2015, 03:06:08 schrieb Tom De Vylder:

Hi  Tom!

I got it ... hopfully.

My changes can be automaticly merged, i can't create a pull-request.?


Greetings,
 Bodo

**Pull request closed without merging**
